#!/usr/bin/env bash
    
[ "$UID" -eq 0 ] || exec sudo "$0" "$@"

AZI_FILES_DIR="/usr/share/azilink-desktop"

AZI_USAGE="$(basename "$0") [-h] [-p path] -- azilink pc companion

where:
    -h/--help               show this help text and exit
    -p/--path path_to_dir   set a new custom path to a folder with azilink.ovpn and resolv.conf files (default is '$AZI_FILES_DIR')"

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) echo "$AZI_USAGE"; exit 0;;
        -p|--path) AZI_FILES_DIR="$2"; shift ;;
        *) echo "Unknown parameter passed: $1" >&2; echo "$AZI_USAGE" >&2; exit 1 ;;
    esac
    shift
done

log() {
    local TIME_NOW=`date "+%Y-%m-%d %H:%M:%S.%5N"`
    echo "[$TIME_NOW] azilink: $@"
}

start() {
    log "Killing openvpn if running..."
    pkill openvpn

    log "Shutting down NetworkManager..."
    systemctl stop NetworkManager

    log "Updating resolv.conf..."
    cp "$AZI_FILES_DIR/resolv.conf" /etc/
}

main() {
    adb forward tcp:41927 tcp:41927
    modprobe tun

    log "Starting OpenVPN connection..."
    openvpn --config "$AZI_FILES_DIR/azilink.ovpn"
}

finish() {
    log "Starting NetworkManager..."
    systemctl start NetworkManager

    log "Exiting..."
    exit 0
}

start
main
finish
